version: '3.8'

services:
  sample-authorizationservice:
    image: ${DOCKER_REGISTRY-}sample-authorizationservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - '5234:80'
      - '7178:443'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: Sample.AuthorizationService.Web/Dockerfile

  sample-database-server:
    container_name: sample-database-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: '#&E*ye76t&#YGet8q7#*&YTtw8qytt&E7t378ET78etW*87'
      ACCEPT_EULA: 'Y'
